-- MySQL Script generated by MySQL Workbench
-- Sun May  7 15:20:50 2017
-- Model: Meme Me    Version: 3.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema garethnu_memes
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema app_memes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema app_memes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `app_memes` ;
USE `app_memes` ;

-- -----------------------------------------------------
-- Table `app_memes`.`meme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_memes`.`meme` (
  `idmeme` INT NOT NULL,
  `iduser` INT NULL COMMENT 'The user that posted it',
  `thumb` VARCHAR(150) NULL COMMENT 'Full URL to thumbnail',
  `full` VARCHAR(150) NULL COMMENT 'Full URL to large image',
  `link` VARCHAR(150) NULL COMMENT 'Full URL to the meme on the web server',
  `epoch` INT UNSIGNED NULL COMMENT 'Order by this',
  `ago` VARCHAR(10) NULL,
  `caption` VARCHAR(140) NULL,
  `lat` DECIMAL(10,6) NULL,
  `long` DECIMAL(10,6) NULL,
  `original_post` INT NULL COMMENT 'Id of the original post (if it’s a repost)',
  `original_poster` INT NULL COMMENT 'id of the original poster (if it’s a repost)',
  `stars-num` INT NULL,
  `comments-num` INT NULL,
  `comments` TINYTEXT NULL,
  `reposts-num` INT NULL,
  `reposted` TINYINT(1) NULL COMMENT 'Whether the user has reposted this post',
  `repostable` TINYINT(1) NULL COMMENT 'Whether the meme is reportable',
  PRIMARY KEY (`idmeme`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_memes`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_memes`.`user` (
  `iduser` INT NOT NULL,
  `username` VARCHAR(50) NULL,
  `firstName` VARCHAR(60) NULL,
  `surname` VARCHAR(60) NULL,
  `name` VARCHAR(121) NULL COMMENT 'Length allows for firstName + surname',
  `pic` VARCHAR(150) NULL COMMENT 'Full URL to profile pic',
  `isFollowing` TINYINT(1) NULL COMMENT 'Whether the user is following them',
  `you` TINYINT(1) NULL COMMENT 'To save comparing with stored user id',
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
