-- MySQL Script generated by MySQL Workbench
-- Sat Apr 22 19:06:21 2017
-- Model: Memes    Version: 2.1
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema garethnu_memes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema garethnu_memes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `garethnu_memes` DEFAULT CHARACTER SET utf8 ;
USE `garethnu_memes` ;

-- -----------------------------------------------------
-- Table `garethnu_memes`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garethnu_memes`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `ukey` VARCHAR(255) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `emailcode` VARCHAR(45) NULL DEFAULT NULL,
  `firstName` VARCHAR(60) NOT NULL,
  `surname` VARCHAR(60) NOT NULL,
  `picUri` VARCHAR(150) NULL DEFAULT NULL,
  `lat` DECIMAL(10,6) NULL DEFAULT NULL,
  `long` DECIMAL(10,6) NULL DEFAULT NULL,
  `joined` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `notifications` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`iduser`, `ukey`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garethnu_memes`.`meme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garethnu_memes`.`meme` (
  `idmeme` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT NOT NULL,
  `sizes` VARCHAR(150) NOT NULL,
  `ext` VARCHAR(10) NOT NULL,
  `caption` VARCHAR(140) NULL DEFAULT NULL,
  `posted` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `latitude` DECIMAL(10,6) NULL DEFAULT NULL,
  `longitude` DECIMAL(10,6) NULL DEFAULT NULL,
  `share` INT NULL,
  PRIMARY KEY (`idmeme`),
  INDEX `userMeme_idx` (`iduser` ASC),
  INDEX `share_idx` (`share` ASC),
  CONSTRAINT `userMeme`
    FOREIGN KEY (`iduser`)
    REFERENCES `garethnu_memes`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `share`
    FOREIGN KEY (`share`)
    REFERENCES `garethnu_memes`.`meme` (`idmeme`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garethnu_memes`.`star`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garethnu_memes`.`star` (
  `idmeme` INT NOT NULL,
  `iduser` INT NOT NULL,
  `starred` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idmeme`, `iduser`),
  INDEX `likeMeme_idx` (`idmeme` ASC),
  INDEX `likeUser` (`iduser` ASC),
  CONSTRAINT `likeMeme`
    FOREIGN KEY (`idmeme`)
    REFERENCES `garethnu_memes`.`meme` (`idmeme`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `likeUser`
    FOREIGN KEY (`iduser`)
    REFERENCES `garethnu_memes`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garethnu_memes`.`reply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garethnu_memes`.`reply` (
  `idreply` INT NOT NULL AUTO_INCREMENT,
  `idmeme` INT NOT NULL,
  `iduser` INT NOT NULL,
  `reply` VARCHAR(140) NOT NULL,
  `replyed` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idreply`),
  INDEX `commentMeme_idx` (`idmeme` ASC),
  INDEX `commentUser_idx` (`iduser` ASC),
  CONSTRAINT `commentMeme`
    FOREIGN KEY (`idmeme`)
    REFERENCES `garethnu_memes`.`meme` (`idmeme`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `commentUser`
    FOREIGN KEY (`iduser`)
    REFERENCES `garethnu_memes`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garethnu_memes`.`follow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garethnu_memes`.`follow` (
  `follower` INT NOT NULL,
  `followee` INT NOT NULL,
  `followed` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `userFollower_idx` (`follower` ASC),
  INDEX `userFollowee_idx` (`followee` ASC),
  PRIMARY KEY (`follower`, `followee`),
  CONSTRAINT `userFollower`
    FOREIGN KEY (`follower`)
    REFERENCES `garethnu_memes`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `userFollowee`
    FOREIGN KEY (`followee`)
    REFERENCES `garethnu_memes`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
